"""Deleting email field in Users model

Revision ID: 3248f64a6712
Revises: aa6004eb53f7
Create Date: 2023-06-21 15:26:25.710546

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3248f64a6712'
down_revision = 'aa6004eb53f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
